name: grab_test
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - numpy=2.0.1
  - pandas=2.2.3
  - scipy
  - matplotlib
  - flask=3.1.0
  - flask-cors=3.0.10
  - requests=2.32.3
  - pyyaml=6.0.2
  - tqdm=4.67.1
  - pymongo
  - transformers==4.51.3
  - datasets==3.3.2
  - huggingface_hub==0.30.2
  - tokenizers==0.21.0
  - safetensors==0.5.3
  - aiohttp==3.11.10
  - dill==0.3.8
  - multiprocess==0.70.15
  - fsspec==2024.12.0
  - filelock==3.17.0
  - bottleneck==1.4.2
  - numexpr==2.10.1
  - sympy==1.13.3
  - python-dotenv==1.0.1
  - redis-py
  - sentence-transformers=4.1.0
  - google-genai
